### ISSUE TITLE
Reading registry.toml many times

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#104]
I did a custom `open` command for Pkg3 and recorded every time a file was opened and prints the count after each command. Here is some output:

```jl
pkg> add DataFrames
INFO: Resolving package versions
INFO: Updating "Project.toml"
 [no changes]
INFO: Updating "Manifest.toml"
 [no changes]
"/Users/kristoffer/.julia/registries/Uncurated/registry.toml"=>10
"/Users/kristoffer/.julia/registries/Uncurated/D/DataFrames/package.toml"=>3
"/Users/kristoffer/.julia/v0.6/Pkg3/Project.toml"=>3
"/Users/kristoffer/.julia/v0.6/Pkg3/Manifest.toml"=>3
"/Users/kristoffer/.julia/registries/Uncurated/J/JSON/dependencies.toml"=>2
"/Users/kristoffer/.julia/registries/Uncurated/C/Compat/versions.toml"=>2
"/Users/kristoffer/.julia/registries/Uncurated/F/FileIO/dependencies.toml"=>2
"/Users/kristoffer/.julia/registries/Uncurated/F/FileIO/versions.toml"=>2
....
```

It seems suspect that we are opening `registry.toml` 10 times for one command. Should be able to do better.

**Comment by StefanKarpinski** [comment]
I agree. I thought I had pretty carefully architected the `EnvCache` stuff so that we didn't do this, but perhaps I missed something and/or it has regressed since my initial design. It would also make sense to separate the `EnvCache` from a layer of `RegistryCache` objects since registries can be shared between different environments and with the new `LOAD_PATH` stuff we may end up referencing the same registries from multiple environments. Definitely worth some careful engineering here – we should ideally only open and scan each file once.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg3.jl/blob/d0015098516f244aefdbd9d4a60b687adf7b34c2/src/Operations.jl#L183 looks suspicious.

(both the try catch and the loop to call `registered_name`).

**Comment by KristofferC** [comment]
Okay, it is the call to `find_registered!` in the `deps_graph` loop. Perhaps that is ok?

**Comment by KristofferC** [comment]
We could just read the whole shablong into a dictionary and look into that one. Might be easier than to construct these kinda complicated regular expressions and iterator over each line multiple times.

**Comment by KristofferC** [comment]
On the other hand, calling `find_registered!` takes like 0.001 seconds on my computer...

**Comment by StefanKarpinski** [comment]
You like this being fast, right? 😛

**Comment by KristofferC** [comment]
Gotta go fast...

**Comment by KristofferC** [comment]
I think these readings are expected.

**Comment by StefanKarpinski** [comment]
We can always work on minimizing this further in the future.
