### ISSUE TITLE
What happens if you add a package with the same name as the current project

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#204]
Likely not a good idea... Should decide what to do and test it.

**Comment by StefanKarpinski** [comment]
As far as I can tell, this needs to be an error or ignored: names are unique and since each module has a self reference, at least in the top-level module of the project the name of the project must be self-referential. If someone adds the project to itself, we can just ignore it. If they try to add something different by that name then it must be an error.

**Comment by KristofferC** [comment]
Errors now
