### ISSUE TITLE
Updating dependencies on `add`

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#211]
Pkg3 updates dependencies (those not in the project) when you `add` a package. This is a little bit iffy, why should you update `Compat` just because you added some other random package that has nothing to do with Compat. At the same time, you might not want to lock down all your dependencies when you add a package because that might be too inflexible.

**Comment by StefanKarpinski** [comment]
The ideal behavior here would be to leave dependencies unchanged _if possible_ and in general to change as few dependencies as possible. Unfortunately, I don't think the resolver can currently do that computation, which is why it does what it does now. But yes, it's not ideal

**Comment by KristofferC** [comment]
Right now, I guess the "object function" is to maximize version used in all cases, while for us, when adding packages, keeping the current version is more important. Any thoughts about this @carlobaldassi?

**Comment by carlobaldassi** [comment]
I'd need some more detail here. From what I understand, the desired behavior would be to behave as if the currently installed packages were fixed, and try to add a new one. (This could mean that you may get a lower version of that package, right?) If that succeeds, it's ok. But if it fails, then we would need to retry, releasing the constraints on the currently installed packages. At that point, we need to state precisely what "change as few dependencies as possible" means.

Does it mean "minimizing the difference between the current versions (all summed together, see note below) and the new versions (again all summed together) subject to the constraint that at least some version of the added package can be installed?
Or would it be the *number* of dependencies changed that should be minimized? (If so, which ones?) 
Or something else?

The first option seems more doable, although not easy at all (in fact, I'm not *really* sure it's doable, I'd need to think about a way to do it); it would certainly be a bit problematic since the assumption that one always wants to maximize versions is used for version pruning and for the greedy algorithm.

The version that tries to minimize the number of changes may be approached perhaps by some heuristic algorithm that monitors where conflict arise, tries to guess what constraints to release (I'm not sure how, would also need to think about it), and starts over. But as dependency relations can produce arbitrarily complicated situations that's guaranteed to be sub-optimal.

(Note: "all summed together" means a hierarchical value computed as the sum of all major, then minor, then patch, as in the rest of the code.)

Also: would this new objective (to try to keep the installed packages fixed) involve only explicitly required packages, or all of them? Or perhaps all of them, but with the explicitly required ones taking precedence?

**Comment by StefanKarpinski** [comment]
Honestly, I don't think we should worry about this right now. Yes, it's less than ideal but we can change and improve the resolver at any point in time.

**Comment by KristofferC** [comment]
Alright, let's worry about this later. Thanks for your input @carlobaldassi!

**Comment by cstjean** [comment]
Naive proposal:

I would like `add P` to install the same package versions as it would have installed at the time-of-the-last-update of the current environment. I'm fine if the `resolve` occasionally means downgrading other packages, since that's unavoidable, but this definition should minimize how often that happens. It's essentially the 0.6 behavior, right? That's why there was a warning that `METADATA` was out of date.

Concretely, that would entail maintaining a set of per-environment (and per-package?) upper-bounds on package versions, `maxversion[env, pkg]` , that would only be updated when `update` or `update SomePkg` is called.
