### ISSUE TITLE
dev Compat gives v0.0.0

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/Pkg3.jl#248]
```
(v0.7) pkg> status
Status `~/.julia/environments/v0.7/Project.toml`

(v0.7) pkg> add Compat
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [34da2185] + Compat v0.62.1
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [34da2185] + Compat v0.62.1
 [2a0f44e3] + Base64 
# ...
 [4ec0a83e] + Unicode 

(v0.7) pkg> dev Compat
  Updating git-repo `https://github.com/JuliaLang/Compat.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [34da2185] ↓ Compat v0.62.1 ⇒ v0.0.0 [`~/.julia/dev/Compat`]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [34da2185] ↓ Compat v0.62.1 ⇒ v0.0.0 [`~/.julia/dev/Compat`]

(v0.7) pkg> status
Status `~/.julia/environments/v0.7/Project.toml`
 [34da2185] Compat v0.0.0 [`~/.julia/dev/Compat`]
```
Shouldn't the version be `v0.62.1+` or similar? The current situation is unfortunate because it makes adding other packages (with dependencies on Compat) impossible. (The checked out version in `~/.julia/dev/Compat` is current master, that works.)

**Comment by KristofferC** [comment]
If the package contains a Project.toml file then it will use that to determine the version of the package. Since Compat.toml doesn't have a version entry, it defaults to 0.0. So the correct solution is in my view to add a version entry to Compat so we can figure out what the version is.

For (old) packages without a Project file, we just use the latest registered version + epsilon as the version. But this might, of course, be wrong if we checkout some arbitrary commit, which is why using the Project file is much better.

**Comment by martinholters** [comment]
Ah, I see. What's the recommended workflow when to bump the version in Project.toml? Should the last change before tagging a release or the first change after tagging bump the version? And I don't think it's needed, but is there any way to fixup the past releases of Compat which have a Project.toml but no version entry?

> Perhaps a warning for this would make sense while people are transitioning...

Yes. Keeping the issue open for that.

**Comment by KristofferC** [comment]
This version is only used when we get the package in some other way then from the registry (since then we already know the version). So when you develop a package, or add it at some branch / commit.

> Ah, I see. What's the recommended workflow when to bump the version in Project.toml?

Just before tagging.

> And I don't think it's needed, but is there any way to fixup the past releases of Compat which have a Project.toml but no version entry?

This only matters when you are checking out (or developing) a package so I am not sure there is a big need to fixup anything.

**Comment by StefanKarpinski** [comment]
> If the package contains a Project.toml file then it will use that to determine the version of the package. Since Compats project file doesn't have a version entry, it defaults to 0.0.

Would it make more sense to only derive the version from the project file if it has a `version` entry?

**Comment by KristofferC** [comment]
Yeah, I guess. But at the same time, if you add a project file to the package, just add the version as well... It's hard to support packages that are half old and half new.

**Comment by StefanKarpinski** [comment]
Don't I know it. Bit it doesn't seem that hard in this case since we already have to code to figure out the version number when there's no project file present. Just make the condition for invoking that code whether the project file has a `version` entry instead of whether the project file exists or not.

**Comment by martinholters** [comment]
So what kind of workflow should attobot ideally provide? Listen on commits to the master branch and be triggered when the version entry is bumped?

**Comment by KristofferC** [comment]
Perhaps easier to keep tagging like now but just check the Project file for the version instead of the tag name? Or enforce that the tag name and the project version are consistent with eachother.
