### ISSUE TITLE
add precompiles file

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg3.jl#28]
Startup time is really slow even with precompilation. Presumably having a precompiles file would help that out, so it's worth trying. I guess the way to do this these days is with SnoopCompile?

**Comment by KristofferC** [comment]
I will try it out and see if it improves stuff.

**Comment by KristofferC** [comment]
I wonder if the load time is long because we overwrite methods and thereby possible invalidate a 
lot of other methods?

Anyway, snoop compile by itself actually increased `import Pkg3` from 1.08 to 1.88 seconds. It also didn't really help with time to first call. However, adding a `Base.require(:Pkg3)` to `userimg.jl` and recompiling made stuff feel a lot faster (and this is probably how it will be released) so that's reassuring.

**Comment by KristofferC** [comment]
Here's the branch https://github.com/KristofferC/Pkg3.jl/tree/kc/precompile

**Comment by StefanKarpinski** [comment]
> I wonder if the load time is long because we overwrite methods and thereby possible invalidate a
> lot of other methods?

Oh yeah, that is entirely possible.

**Comment by KristofferC** [comment]
I could try a version of Julia where it is possible to plugin into the loading system instead of overwriting methods. Would give a sense of what the cost of method overwrites are.

**Comment by KristofferC** [comment]
Done
