### ISSUE TITLE
Dry runs (non modificating) execution of commands

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#34]
Perhaps it would be a good idea to be able to run the commands in a "dry mode" where the command is run but no modifications are made to anything.

This could be a good way to allow people to explore different commands without being scared of messing up something.

**Comment by StefanKarpinski** [comment]
I was kind of hoping that checking project and manifest files into git would address that since you can always get back to a previous state just by doing a `git checkout Project.toml Manifest.toml`. Thought about having a `pkg> reset` or something. Perhaps we could have some kind of `pkg> undo` command? This would require keeping a per-environment log of operations and then updoing them, but we could do that. Would only operate on the project and manifest files since everything else should not need undoing, being immutable and all.

**Comment by KristofferC** [comment]
Yeah, perhaps `git checkout` is enough. I was thinking that it would skip downloading, building etc as well but perhaps this is just overkill.

**Comment by StefanKarpinski** [comment]
I guess that could be useful, kind of a "preview" feature? So maybe `pkg> preview add Gadfly` would show you all the things that *would* be installed and added to the project & manifest. I kind of like that – sometimes you do really want to know what effect something will have *before* doing it.

**Comment by KristofferC** [comment]
Fixed by #35
