### ISSUE TITLE
Error printing of dependent packages in resolution failure

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#50]
Packages that are "discovered" during creation of the dependency graph are not added to the UUID -> name dictionary that is sent to the resolver, and are thereby not printed by name when resolution fails.

Ref https://github.com/JuliaLang/Pkg3.jl/issues/10

**Comment by StefanKarpinski** [comment]
I guess the solution is to add them to the `UUID -> name` dict when they're discovered? One implementation design criterion here is that you want to scan the `registry.toml` file as little as possible and avoid repeated parsing of the same TOML files in the registry tree. That's why the `EnvCache` object tends to cache more than strictly necessary and have APIs for doing batch-oriented parsing rather than doing one thing at a time. This approach is key to Pkg3's speed.

**Comment by KristofferC** [comment]
I think this is done now.
